//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chimera.Authentication.Web.Resources.AuthWeb", typeof(AuthWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already in use.
        /// </summary>
        public static string DuplicateEMail {
            get {
                return ResourceManager.GetString("DuplicateEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID provided by the external service is already in use.
        /// </summary>
        public static string DuplicateProviderUserKey {
            get {
                return ResourceManager.GetString("DuplicateProviderUserKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is already used.
        /// </summary>
        public static string EMailAlreadyInUse {
            get {
                return ResourceManager.GetString("EMailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not used.
        /// </summary>
        public static string EMailNotInUse {
            get {
                return ResourceManager.GetString("EMailNotInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you do not have an account yet.
        /// </summary>
        public static string IfNoAccountYet {
            get {
                return ResourceManager.GetString("IfNoAccountYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name - only letters, digits, hyphen, underscore and period is allowed (a-z, 0-9, -, _, .)..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with user name and password in order to connect with &lt;strong&gt;{1}&lt;/strong&gt; at &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string LoginUnknownExternal_p2 {
            get {
                return ResourceManager.GetString("LoginUnknownExternal_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using existing account.
        /// </summary>
        public static string LoginUsingExistingAccount {
            get {
                return ResourceManager.GetString("LoginUsingExistingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in as existing user and connect with {0}.
        /// </summary>
        public static string LoginWithExternalLogin_p1 {
            get {
                return ResourceManager.GetString("LoginWithExternalLogin_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also login from one of these services.
        /// </summary>
        public static string LoginWithExternalService {
            get {
                return ResourceManager.GetString("LoginWithExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {2} characters long.
        /// </summary>
        public static string p0_MustBe_p2_CharsLong {
            get {
                return ResourceManager.GetString("p0_MustBe_p2_CharsLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adgangskode.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string PasswordAndConfirmationDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordAndConfirmationDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register {0} as a new user.
        /// </summary>
        public static string RegisterExternalLogin_p1 {
            get {
                return ResourceManager.GetString("RegisterExternalLogin_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as new user and connect with &lt;strong&gt;{1}&lt;/strong&gt; at &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string RegisterUnknownExternal_p2 {
            get {
                return ResourceManager.GetString("RegisterUnknownExternal_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also register with one of these services.
        /// </summary>
        public static string RegisterWithExternalService {
            get {
                return ResourceManager.GetString("RegisterWithExternalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string Required_p0 {
            get {
                return ResourceManager.GetString("Required_p0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully authenticated with &lt;strong&gt;{0}&lt;/strong&gt; as &lt;strong&gt;{1}&lt;/strong&gt;. We do not know that account - what would you like to do?.
        /// </summary>
        public static string SuccessfullExternalAuthentication_p2 {
            get {
                return ResourceManager.GetString("SuccessfullExternalAuthentication_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is available.
        /// </summary>
        public static string UserNameAvailable {
            get {
                return ResourceManager.GetString("UserNameAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name is already taken by another.
        /// </summary>
        public static string UserNameNotAvailable {
            get {
                return ResourceManager.GetString("UserNameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        public static string Welcome_p0 {
            get {
                return ResourceManager.GetString("Welcome_p0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
